name: Build and Release
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '21.0.1'
          distribution: 'liberica'
      - run: ./gradlew shadowJar
      - uses: actions/upload-artifact@v3
        with:
          name: github-actions-artifact
          path: |
            build/libs/*all.jar
      - id: create_release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            build/libs/*all.jar
